### ISSUE TITLE
Improve API

### ISSUE THREAD

**Issue by dlfivefifty** [RalphAS/Pseudospectra.jl#1]
I just came across this package and it looks great! Looking forward to seeing it develop.

I wanted to suggest improving the user-interface. For example, I'd like to be able to do the following for a quick-and-dirty plot:
```julia
using Pseudospectra, Plots
A = randn(10,10)
pseudospectraplot(A)
```

**Comment by RalphAS** [comment]
I've added a `spectralportrait` method as documented on the README. Does that seem about right for your purposes?

**Comment by dlfivefifty** [comment]
Yes looks great!
