### ISSUE TITLE
BigFloat support

### ISSUE THREAD

**Issue by sverek** [RalphAS/Pseudospectra.jl#5]
Would be great if BigFloat matrices were supported, a nice improvement to the original EigTool.

**Comment by RalphAS** [comment]
Currently the core of the package should work on `BigFloat` and other non-BLAS-type matrices; one needs to load the `GenericSVD` and `GenericSchur` packages to allow this.  At the moment the `PyPlot` backend is problematic for `BigFloat`, but `Plots` should be compatible.

I'll try to patch the `PyPlot` interface soon.  Let me know if you are interested in (and having trouble with) the extended functionality (i.e. not just spectral portraits) for `BigFloat`. I haven't tested that so far.

**Comment by RalphAS** [comment]
I've cleaned up the handling of extended precision in the core routines and documented it. Note that overloads from both GenericLinearAlgebra and GenericSchur are needed for this.
